[package]
name = "note"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
regex = "1.12.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_cbor = "0.11.2"
uuid = { version = "1.18.1", features = ["v4"] }
